# name: Run Tests and Send Email on Failure

# on:
#   push:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.11'

#       - name: Install Poetry
#         run: |
#           curl -sSL https://install.python-poetry.org | python3 -
#           echo "$HOME/.local/bin" >> $GITHUB_PATH

#       - name: Install dependencies
#         run: |
#           cd src
#           poetry install

#       - name: Run tests
#         id: run_tests
#         run: |
#           cd src
#           poetry run pytest -v

#       - name: Send email if tests fail
#         if: failure()
#         uses: dawidd6/action-send-mail@v3
#         with:
#           server_address: smtp.office365.com
#           server_port: 587
#           username: ${{ secrets.EMAIL_USERNAME }}
#           password: ${{ secrets.EMAIL_PASSWORD }}
#           subject: "🚨 Test Failed in Airflow Repo"
#           body: "Some tests failed in the latest push to main. Please check the Actions tab on GitHub."
#           to: dmajumder@corecommodityllc.com
#           from: ${{ secrets.EMAIL_USERNAME }}
name: Run Tests and Auto-Merge to Main on Success

on:
  push:
    branches-ignore:
      - main  # Prevent direct pushes to main from triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          cd src
          poetry install

      - name: Run tests
        id: run_tests
        run: |
          cd src
          poetry run pytest -v

      - name: Send email if tests fail
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚨 Test Failed in Airflow Repo"
          body: "Some tests failed in the latest push. Please check the Actions tab on GitHub."
          to: dmajumder@corecommodityllc.com
          from: ${{ secrets.EMAIL_USERNAME }}

  merge:
    needs: test
    if: ${{ needs.test.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge to main if tests pass
        uses: devops-infra/action-pull-request@v0.5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ github.ref_name }}
          target_branch: main
          title: "Auto-merge: ${{ github.ref_name }}"
          body: "Tests passed. Auto-merging to main."


#new